[[redirects]]
  from = "/api/*"
  to = "https://tea-zagrodnicy.koyeb.app/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
