insert into category (id, name, type) values (1, 'at velit vivamus', 'EXPENSE');
insert into category (id, name, type) values (2, 'etiam faucibus cursus', 'INCOME');
insert into category (id, name, type) values (3, 'at', 'INCOME');
insert into category (id, name, type) values (4, 'sed', 'INCOME');
insert into category (id, name, type) values (5, 'nulla', 'EXPENSE');
insert into category (id, name, type) values (6, 'in hac habitasse', 'EXPENSE');
insert into category (id, name, type) values (7, 'dapibus nulla suscipit', 'EXPENSE');
insert into category (id, name, type) values (8, 'quam', 'EXPENSE');
insert into category (id, name, type) values (9, 'morbi vel lectus', 'EXPENSE');
insert into category (id, name, type) values (10, 'non interdum in', 'INCOME');
insert into category (id, name, type) values (11, 'nullam porttitor lacus', 'EXPENSE');
insert into category (id, name, type) values (12, 'justo pellentesque', 'INCOME');
insert into category (id, name, type) values (13, 'justo', 'EXPENSE');
insert into category (id, name, type) values (14, 'purus phasellus in', 'EXPENSE');
insert into category (id, name, type) values (15, 'molestie lorem', 'EXPENSE');
insert into category (id, name, type) values (16, 'vivamus vestibulum', 'INCOME');
insert into category (id, name, type) values (17, 'vel pede', 'INCOME');
insert into category (id, name, type) values (18, 'eros viverra eget', 'EXPENSE');
insert into category (id, name, type) values (19, 'sagittis', 'INCOME');
insert into category (id, name, type) values (20, 'non mattis', 'INCOME');
