name: Run Tests

on: [push, fork]

jobs:
  run_tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js@16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Check Formatting
        run: yarn format:check

      - name: Run tests
        run: yarn test:headless

      - name: Build
        run: yarn build:prod
